source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-default-layout'
gem 'tzinfo-data'
gem 'jekyll-remote-theme', "0.4.0"
gem 'wdm', :install_if => Gem.win_platform?
# ignore this please
