container:
  image: squidfunk/mkdocs-material:4.4.0

docs_deploy_task:
  env:
    DEPLOY_TOKEN: ENCRYPTED[8b719b51d75561d87baa92c15925d77ddce4a78bd31b1b87b48f1ca0931bd7b968357edf401e0ecbc2a0e8c49ea8cbff]
  install_script: pip install --upgrade pymdown-extensions
  skip: $CIRRUS_BRANCH != 'master'
  deploy_script: |
    git config --global user.name "Cirrus CI"
    git config --global user.email "support@rdil.rocks"
    git remote set-url origin https://$DEPLOY_TOKEN@github.com/annieapp/annie/
    mkdocs gh-deploy --force --remote-branch gh-pages

docs_test_task:
  install_script: pip install --upgrade pymdown-extensions
  build_script: mkdocs build
  docs_build_artifacts:
    path: site/**

frontend_tests_task:
  container:
    image: ruby:slim
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
  bootstrap_script: gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: |
      ruby -v
      cat frontend/Gemfile
    populate_script: cd frontend && bundler
  build_and_test_script: cd frontend && bundler exec jekyll build
  site_build_artifacts:
    path: frontend/_site/**/**

server_beta_task:
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: python:slim
  install_script: python3 -m pip install --upgrade --user setuptools wheel
  build_script: python3 setup.py sdist
  download_artifacts:
    path: dist/**

server_unittests_task:
  container:
    image: python:slim
  python_packages_cache:
    folder: /usr/local/lib/python3.7/site-packages
    fingerprint_script: cat requirements.txt && cat .cirrus.yml
    populate_script: python3 -m pip install --upgrade -r requirements.txt
  prep_script: python3 -m pip install --user --upgrade .
  script: python3 -m xmlrunner tests
  always:
    unittest_results_artifacts:
      path: ./*.xml
      format: junit
